### ISSUE TITLE
Issues with cilium enterprise

### ISSUE THREAD

**Issue by 54nd20** [projectsyn/component-cilium#12]
component-cilium is not properly working with cilium-enterprise. 

## Steps to Reproduce the Problem

  1. Install cilium enterprise following https://docs.isovalent.com/v1.10/operations-guide/installation/openshift.html
  2. Enable component-cilium

## Actual Behavior
- component-cilium creates a subscription for cilium, not cilium-enterprise
- component-cilium creates resources named "cilium" instead of "cilium-enterprise".  This leads to conflicting resources being created. For instance:
     -  ciliumconfig
     -  operator
     -  operatorgroup
     -  subscription

## Expected Behavior
* component-cilium creates and manages correct resources

**Comment by glrf** [comment]
We will track this issue in two different feature requests #16 and #17

**Comment by glrf** [comment]
That issue should be resolved. If not please reopen it
