### ISSUE TITLE
[OLM] Component should either install CSV manually (enterprise) or use OLM flow with subscription (opensource), not both

### ISSUE THREAD

**Issue by haasad** [projectsyn/component-cilium#50]
When using the OLM install method, this component creates both a clusterserviceversion (CSV) and an OLM subscription for cilium. This leads to problems with resolving the subscription which in turn leads to a degraded ArgoCD application leading to unnecessary alerts in monitoring.

opensource:
```shell
kubectl -n cilium get sub cilium -oyaml | yq e '.status.conditions[-1]' -
message: 'constraints not satisfiable: clusterserviceversion cilium.v1.11.5-xf646bca exists and is not referenced by a subscription, @existing/cilium//cilium.v1.11.5-xf646bca and certified-operators/openshift-marketplace/1.11/cilium.v1.11.5-xf646bca provide CiliumConfig (cilium.io/v1alpha1), subscription cilium requires certified-operators/openshift-marketplace/1.11/cilium.v1.11.5-xf646bca, subscription cilium exists'
reason: ConstraintsNotSatisfiable
status: "True"
type: ResolutionFailed

```

enterprise:
```shell
kubectl -n cilium get sub cilium-enterprise -oyaml | yq e '.status.conditions[-1]' -        
message: 'constraints not satisfiable: no operators found in channel stable of package cilium-enterprise in the catalog referenced by subscription cilium-enterprise, subscription cilium-enterprise exists'
reason: ConstraintsNotSatisfiable
status: "True"
type: ResolutionFailed
```

## Steps to Reproduce the Problem

  1. check the subscriptions on a cluster with olm install method

## Actual Behavior

Installing the CSV directly and adding a subscription leads to resolution failures for the subscription

## Expected Behavior

opensource:
- ideally the component would follow the OLM flow as described here: https://github.com/cilium/cilium-olm/issues/45#issuecomment-1116850814
- only add a subscription (maybe with automatic install plan approval), but not directly a CSV

enterprise:
- because there are now operators available in the cilium enterprise channel the CSV should be installed directly by the component
- the component shouldn't add a subscription at all for enterprise

**Comment by glrf** [comment]
We'd actually propose to only create the CSV and no Subscription, even for the open source version. By simply installing a CSV without subscription, we get full control over the installed version through Project Syn and we don't have to worry about the Subscription being unhealthy for a variety of reasons.
